### ISSUE TITLE
multiple calls to SSL_library_init() in multithreaded env.

### ISSUE THREAD

**Issue by mpoul** [CESNET/canl-c#7]
Michail Salichos reported in GGUS ticket #106533:

 We get the crash below frequently, FTS3 servers are multithreaded and users may be delegating concurrently. Pls mind we are already using openssl and crypto locking callbacks, and helgrind/drd report accordingly that a mutex is locked.

However, for every gridsite/canl operation, canl is calling SSL_library_init, which is not appropriate. Could you pls make sure it's called once to avoid this unfortunate situation?
Thanks,
Michail

**Comment by kouril** [comment]
This should be fixed by commit aff501c
